# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e6dd975dd22de3692ebb92ea00c013096412242c28f10d33773040f7c982de1562b2d8b8e0439bb373ab3dabb2f9a647b7f3d846e9c09ec2e4a111b0c2222b

test:
  secret_key_base: c0cc828eec8d6010c8f3ab30e5343c117afecb37ee7a8c0347d558a1fa148419a81d97a644405864b621caa2cdd03bfe6bbde6d6ee926357093cbde43bed89e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
